### ISSUE TITLE
will support last version 4.2.2 of ZeroMQ?

### ISSUE THREAD

**Issue by berryxia** [zedalaye/Delphi-ZeroMQ#1]
Dear Sir:
As you know, The ZeroMQ have the last version of 4.2.2.
so, can you support this?
great thanks.

**Comment by ritalin** [comment]
In 4.2.1, raised Access Violation.

But modifying `zmq_msg_t` record definition led to drop error.

line 132 in zmq.pas
```delphi
-    _: Array[0..32-1] of Byte;
+    _: Array[0..64-1] of Byte;
```

Also version of 4.2.2 may be OK.

For your reference ...

**Comment by zedalaye** [comment]
Hello, this project is not maintained. 

We have worked with ZeroMQ so Delphi bindings are generated automatically following ZMQ API changes.

You will find them in the bindings\delphi subdirectory.

https://github.com/zeromq/czmq/tree/master/bindings/delphi
https://github.com/zeromq/zyre/tree/master/bindings/delphi
